name: Lex Test
on: 
  push:
    branches: [main]
jobs:
  test:
    name: Test GH action
    runs-on: ubuntu-latest
    steps:
    - name: Checking out my beautiful code
      uses: actions/checkout@v3
    - name: Setup PHP with grpc
      uses: shivammathur/setup-php@v2
      with:
        extensions: grpc
    - name: Run composer update
      run: composer update
    - name: Run phpunit
      run: |
        ./vendor/bin/phpunit tests/OperationsTest.php
