name: Lex Test
on: push
jobs:
  test:
    name: Test GH action
    runs-on: ubuntu-latest
    steps:
    - name: Checking out my beautiful code
      uses: actions/checkout@v3
    - name: Setup PHP with grpc
      uses: shivammathur/setup-php@v2
      with:
        extensions: grpc
    - name: Output list of files
      run: |
        ls
