name: Lex Test
on: push
jobs:
  test:
    name: Test GH action
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP with grpc
      uses: shivammathur/setup-php@v2
      with:
        extensions: grpc
    - name: Output PHP version and grpc status
      run: |
        php -v
        php -m | grep grpc
